web:
  image: nginx
  volumes:
   - /home/nc-user/Docker/nginx/etc:/etc/nginx
  ports:
   - "8080:80"
  environment:
   - NGINX_HOST=ascii.in.th
   - NGINX_PORT=80
  command: [nginx, '-g', 'daemon off;']